import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { BottomNav } from "@/components/BottomNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <section className="flex flex-col ">
      <div className="pb-16 h-screen">{children}</div>
      <BottomNav />
    </section>
  );
}
